default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  host: localhost
  database: tinylog_dev
  username: tinyusr
  password: password

test:
  <<: *default
  host: localhost
  database: tinylog_test
  username: tinyusr
  password: password

production:
  url: <%= ENV["DATABASE_URL"] %>
