default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  host: localhost
  database: tinylog_dev
  username: sebastian
  password: pepeloco

test:
  <<: *default
  host: localhost
  database: tinylog_test
  username: sebastian
  password: pepeloco

production:
  url: <%= ENV["DATABASE_URL"] %>
